---
- name: Configure node01
  hosts: node01
  become: yes
  tasks:
    - name: Update apt repository and cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install docker-compose via binary
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify docker-compose installation
      command: docker-compose --version
      register: docker_compose_version
      changed_when: false


    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Copy docker-compose file from manager to node01
      copy:
        src: /home/vagrant/docker-compose.yml
        dest: /home/vagrant/docker-compose.yml
        mode: '0644'

    - name: Copy microservices source code from manager to node01
      copy:
        src: /home/vagrant/services/
        dest: /home/vagrant/
        mode: '0644'


    - name: Start Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/vagrant

