Vagrant.configure("2") do |config|
  # Используем базовый образ Ubuntu 20.04 (Focal Fossa)
  config.vm.box = "ubuntu/focal64"

  # Определяем настройки для каждой машины
  machines = [
    {
      name: "manager",
      hostname: "manager",
      ip: "192.168.56.10",
      ports: [], # Нет проброшенных портов
      memory: 1024, # Память по умолчанию
      cpus: 1       # Количество CPU по умолчанию
    },
    {
      name: "node01",
      hostname: "node01",
      ip: "192.168.56.11",
      ports: [
        { guest: 8081, host: 8081 },
        { guest: 8087, host: 8087 },
        { guest: 5432, host: 5432 },
        { guest: 5672, host: 5672 },
        { guest: 15672, host: 15672 }
      ],
      memory: 2048, # Увеличенная память
      cpus: 1       # Количество CPU по умолчанию
    },
    {
      name: "node02",
      hostname: "node02",
      ip: "192.168.56.12",
      ports: [
        { guest: 80, host: 80 },
        { guest: 5432, host: 5433 }
      ], 
      memory: 1024, # Память по умолчанию
      cpus: 1       # Количество CPU по умолчанию
    }
  ]

  # Создаем виртуальные машины на основе настроек
  machines.each do |machine|
    config.vm.define machine[:name] do |node|
      node.vm.hostname = machine[:hostname]

      # Настройка приватной сети
      node.vm.network "private_network", ip: machine[:ip]

      # Пробрасываем порты, если они указаны
      if machine[:ports].any?
        machine[:ports].each do |port|
          node.vm.network "forwarded_port", guest: port[:guest], host: port[:host]
        end
      end


      # Указываем уникальное имя для VirtualBox с префиксом DO8
      node.vm.provider "virtualbox" do |vb|
        vb.name = "DO8-#{machine[:name]}"
        vb.memory = machine[:memory] # Устанавливаем память для конкретной машины
        vb.cpus = machine[:cpus]     # Устанавливаем количество CPU для конкретной машины
      end
    end
  end
end
